### ISSUE TITLE
Filter chain halted as :verify_signature rendered or redirected 按照教程，报错

### ISSUE THREAD

**Issue by qiao2818** [skinnyworm/wechat-rails#38]
Filter chain halted as :verify_signature rendered or redirected 按照教程，报错

**Comment by qiao2818** [comment]
之前看到被关闭的issue里面也有，但是怎么弄？

**Comment by Eric-Guo** [comment]
一般都是签名不过，请仔细检查[配置](https://github.com/Eric-Guo/wechat#rails-全局配置)是否正确。
